// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4654c4c9-e7de-418b-9817-b26231b43fd1",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_CtxMmVrw1",
    "aws_user_pools_web_client_id": "25al30oc46nv8bsu69m5b0r9h6",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://2og7xddlxbe3rpntcrgfq6i4xa.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "smart-parking-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://smart-parking-dev.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
